Arab : arab 
	./arab
Romawi : romawi 
	./romawi
Boolean : boolean 
	./boolean

arab : Arab_driver.cpp ../Arab.cpp ../ArabExp.cpp ../Ekspresi.cpp ../Aritmatik.cpp
	g++ Arab_driver.cpp ../Arab.cpp ../ArabExp.cpp ../Ekspresi.cpp ../Aritmatik.cpp -o arab -std=c++11

romawi : Romawi_driver.cpp ../Romawi.cpp ../RomawiExp.cpp ../Ekspresi.cpp ../Aritmatik.cpp
	g++ Romawi_driver.cpp ../Romawi.cpp ../RomawiExp.cpp ../Ekspresi.cpp ../Aritmatik.cpp -o romawi

boolean : Boolean_driver.cpp ../Boolean.cpp ../Ekspresi.cpp
	g++ Boolean_driver.cpp ../Boolean.cpp ../Ekspresi.cpp -o boolean